# Generated by Django 3.1 on 2020-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=1, max_length=225, verbose_name='性别(单选)'),
        ),
    ]
