# Generated by Django 3.1.1 on 2020-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossinfo',
            name='userUrl',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='个人主页(URL地址)'),
        ),
    ]
